### ISSUE TITLE
Rewrite tour of Scala

### ISSUE THREAD

**Issue by travissarles** [scala/docs.scala-lang#733]
I'm rewriting most of the tour of Scala. However some guides may not be as relevant like XML processing. Thoughts? @heathermiller 

[The tour](http://docs.scala-lang.org/tutorials/tour/tour-of-scala.html)
[More info on the rewrite](https://contributors.scala-lang.org/t/learning-scala-made-easy-ier/529)

**Current status:** 

- [x] **[Higher-order functions](https://github.com/scala/scala.github.com/pull/699)** ([old version](http://docs.scala-lang.org/tutorials/tour/higher-order-functions.html))
- [x] **[Singleton objects](https://github.com/scala/scala.github.com/issues/704)** ([old version](http://docs.scala-lang.org/tutorials/tour/singleton-objects.html))
- [x] **[Generic classes](https://github.com/scala/scala.github.com/issues/705)** ([old version](http://docs.scala-lang.org/tutorials/tour/generic-classes.html))
- [x] **[Operators](https://github.com/scala/scala.github.com/issues/707)** ([old version](http://docs.scala-lang.org/tutorials/tour/operators.html))
- [x] **[Unified Types](https://github.com/scala/scala.github.com/issues/708)** ([old version](http://docs.scala-lang.org/tutorials/tour/unified-types.html))
- [x] **[Traits](https://github.com/scala/scala.github.com/issues/713)** ([old version](http://docs.scala-lang.org/tutorials/tour/traits.html))
- [x] **[Currying](https://github.com/scala/scala.github.com/issues/732)** ([old version](http://docs.scala-lang.org/tutorials/tour/currying.html))
- [x] **[Classes](https://github.com/scala/scala.github.com/issues/698)** ([old version](http://docs.scala-lang.org/tutorials/tour/classes.html))
- [x] **[Packages and imports](https://github.com/scala/scala.github.com/issues/714)**
- [x] **[Case classes](https://github.com/scala/scala.github.com/issues/715)** ([old version](http://docs.scala-lang.org/tutorials/tour/case-classes.html))
- [x] **[Pattern matching](https://github.com/scala/scala.github.com/issues/717)** ([old version](http://docs.scala-lang.org/tutorials/tour/pattern-matching.html))
- [x] **[Named arguments](https://github.com/scala/scala.github.com/issues/728)** ([old version](http://docs.scala-lang.org/tutorials/tour/named-parameters.html))
- [x] **[Default parameter](https://github.com/scala/scala.github.com/issues/730)** ([old version](http://docs.scala-lang.org/tutorials/tour/default-parameter-values.html))
- [x] [Annotations](https://github.com/scala/scala.github.com/pull/756) ([old version](http://docs.scala-lang.org/tutorials/tour/annotations.html))
- [x] [By-name Parameters](https://github.com/scala/scala.github.com/pull/757) ([old version](http://docs.scala-lang.org/tutorials/tour/automatic-closures.html))
- [x] [Local type inference](https://github.com/scala/scala.github.com/pull/737) ([old version](http://docs.scala-lang.org/tutorials/tour/local-type-inference.html))
- [x] [Polymorphic methods](https://github.com/scala/scala.github.com/pull/740) ([old version](http://docs.scala-lang.org/tutorials/tour/polymorphic-methods.html))
- [x] [Implicit conversions](https://github.com/scala/scala.github.com/pull/746) ([old version](http://docs.scala-lang.org/tutorials/tour/implicit-conversions.html))
- [x] [Implicit parameters](https://github.com/scala/scala.github.com/pull/746) ([old version](http://docs.scala-lang.org/tutorials/tour/implicit-parameters.html))
- [x] [Explicitly typed self references ](https://github.com/scala/scala.github.com/pull/748)([old version](http://docs.scala-lang.org/tutorials/tour/explicitly-typed-self-references.html))
- [x] [Compound types](https://github.com/scala/scala.github.com/pull/742) ([old version](http://docs.scala-lang.org/tutorials/tour/compound-types.html))
- [x] [Abstract types](https://github.com/scala/scala.github.com/pull/759) ([old version](http://docs.scala-lang.org/tutorials/tour/2017-02-13-abstract-types.html))
- [x] [Inner classes](https://github.com/scala/scala.github.com/pull/755) ([old version](http://docs.scala-lang.org/tutorials/tour/inner-classes.html))
- [x] [Lower type bounds](https://github.com/scala/scala.github.com/pull/760) ([old version](http://docs.scala-lang.org/tutorials/tour/lower-type-bounds.html))
- [x] [Upper type bounds](https://github.com/scala/scala.github.com/pull/749) ([old version](http://docs.scala-lang.org/tutorials/tour/upper-type-bounds.html))
- [x] [Variance](https://github.com/scala/scala.github.com/issues/741) ([old version](http://docs.scala-lang.org/tutorials/tour/variances.html)) @mhzajac
- [x] [Sequence comprehensions](https://github.com/scala/scala.github.com/pull/754) ([old version](http://docs.scala-lang.org/tutorials/tour/sequence-comprehensions.html))
- [x] Extractor objects ([old version](http://docs.scala-lang.org/tutorials/tour/extractor-objects.html)) @mhzajac 
- [x] [Regular expression patterns](https://github.com/scala/scala.github.com/pull/758) ([old version](http://docs.scala-lang.org/tutorials/tour/regular-expression-patterns.html))
- [x] [XML processing](https://github.com/scala/scala.github.com/pull/743) ([old version](http://docs.scala-lang.org/tutorials/tour/xml-processing.html))
- [x] [Nested functions](https://github.com/scala/scala.github.com/pull/735) ([old version](http://docs.scala-lang.org/tutorials/tour/nested-functions.html)) @ZeonTrevor
- [x] [Anonymous function syntax](https://github.com/scala/scala.github.com/pull/734) ([old version](http://docs.scala-lang.org/tutorials/tour/anonymous-function-syntax.html))
- [x] [Mix-in class composition](https://github.com/scala/scala.github.com/pull/738) ([old version](http://docs.scala-lang.org/tutorials/tour/mixin-class-composition.html))

When rewriting the tour, the goals should be to:

1. Get people up and running as quickly as possible
2. Be concise without omitting key information
3. Provide enough information so readers can stay on the page and not have to look up a bunch of terminology
4. Cater to readers coming from various popular programming languages and not just Java
5. Don't use language features in examples that haven't been covered yet
6. Try to use examples that might be used in production but not at the expense of clarity
7. Read the comments to figure out where people are confused
8. Link to other pages when it could be helpful

Be sure to add a "prerequisite-knowledge" metadata field to the top of the file. Once the tour is rewritten, we'll use this to make sure there are no forward-references.

**Comment by SethTisue** [comment]
In general, I encourage you to be bold about proposing renaming, merging, and dropping sections. I think there is a lot of room for improvement there.

**Comment by travis032654** [comment]
Yes, I think some of the names are overly complicated and specific

**Comment by heathermiller** [comment]
Woohoo! @mhzajac has contributed the rewritten variance tour. Thank you! @mhzajac, I'll ask around for reviews 🙂

**Comment by mhzajac** [comment]
I can try to grab another off the pile. Maybe extractors?

**Comment by travis032654** [comment]
@mhzajac Sure! That would be great. I'll put your name next to it on the ticket.

**Comment by travissarles** [comment]
@mhzajac will you still be able to do the extractors section? I'm trying to wrap things up today. Thanks again for your help.

**Comment by mhzajac** [comment]
@travissarles Sorry, I'd planned to work on it last week but fell short on spare time. I was going to try again in the latter half of this week, but if you're looking to wrap it up today, I'll have to give it up.

**Comment by travissarles** [comment]
Thanks for the variances section.

**Comment by SethTisue** [comment]
the last PR still left over from Travis's efforts has been merged 🎉
